/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaapplication1;
import java.sql.*; 
/**
 *
 * @author dodz
 */
public class doctor_timing extends javax.swing.JFrame {


    /**
     * Creates new form doctor_timing
     */
    String doctor1_name;
    String doctor2_name;
    String doctor3_name;
    
    String timing1;
    String timing2;
    String timing3;
    
    String post1;
    String post2;
    String post3;
    
    int i=0;
    public doctor_timing() {
        initComponents();
        try{  
            Class.forName("com.mysql.cj.jdbc.Driver");  
            Connection con=DriverManager.getConnection(  
            "jdbc:mysql://localhost:3306/hms","root","12348765");  
            //here sonoo is database name, root is username and password  
            Statement stmt=con.createStatement();  
            ResultSet rs=stmt.executeQuery("select * from doctors");  
            while(rs.next()){
                System.out.println(rs.getString(1));
            if(i==0){
                doctor1_name=rs.getString(1);
                timing1=rs.getString(3);
                post1=rs.getString(2);
//               i++;
                }
                if(i==1)
                {
                    doctor2_name=rs.getString(1);
                    timing2=rs.getString(3);
                    post2=rs.getString(2);
                }
                if(i==2)
                {
                    doctor3_name=rs.getString(1);
                    timing3=rs.getString(3);
                    post3=rs.getString(2);
                }
//            System.out.println(rs.getString(1));
            i++;
             
            
            
            }
            con.close(); 
            }catch(Exception e){ System.out.println(e);};
            doctor1.setText(doctor1_name);
            doctor2.setText(doctor2_name);
            doctor3.setText(doctor3_name);
            
            doctor1_timing.setText(timing1);
            doctor2_timing.setText(timing2);
            doctor3_timing.setText(timing3);
            
            designation1.setText(post1);
            designation2.setText(post2);
            designation3.setText(post3);
            

            
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        availabe_doctors = new javax.swing.JLabel();
        doctor_timings = new javax.swing.JLabel();
        doctor1 = new javax.swing.JLabel();
        doctor2 = new javax.swing.JLabel();
        doctor3 = new javax.swing.JLabel();
        doctor1_timing = new javax.swing.JLabel();
        doctor2_timing = new javax.swing.JLabel();
        doctor3_timing = new javax.swing.JLabel();
        close = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        designation1 = new javax.swing.JLabel();
        designation2 = new javax.swing.JLabel();
        designation3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        availabe_doctors.setText("Names of Available Doctors");

        doctor_timings.setText("Timings");

        doctor1.setText("Doctor Name 1");

        doctor2.setText("jLabel4");

        doctor3.setText("jLabel5");

        doctor1_timing.setText("jLabel6");

        doctor2_timing.setText("jLabel7");

        doctor3_timing.setText("jLabel8");

        close.setText("Close");
        close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeActionPerformed(evt);
            }
        });

        jLabel1.setText("Designation");

        designation1.setText("jLabel2");

        designation2.setText("jLabel3");

        designation3.setText("jLabel4");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(117, 117, 117)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(doctor1)
                    .addComponent(doctor3)
                    .addComponent(doctor2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(doctor3_timing)
                    .addComponent(doctor2_timing)
                    .addComponent(doctor1_timing))
                .addGap(64, 64, 64))
            .addGroup(layout.createSequentialGroup()
                .addGap(254, 254, 254)
                .addComponent(close)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(availabe_doctors)
                .addGap(114, 114, 114)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(designation2)
                            .addComponent(designation1)
                            .addComponent(designation3))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(204, 204, 204)
                .addComponent(doctor_timings)
                .addGap(116, 116, 116))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(availabe_doctors)
                    .addComponent(doctor_timings)
                    .addComponent(jLabel1))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(doctor1)
                    .addComponent(doctor1_timing)
                    .addComponent(designation1))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(doctor2)
                    .addComponent(doctor2_timing)
                    .addComponent(designation2))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(doctor3)
                    .addComponent(doctor3_timing)
                    .addComponent(designation3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addComponent(close)
                .addGap(33, 33, 33))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeActionPerformed
        System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_closeActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel availabe_doctors;
    private javax.swing.JButton close;
    private javax.swing.JLabel designation1;
    private javax.swing.JLabel designation2;
    private javax.swing.JLabel designation3;
    private static javax.swing.JLabel doctor1;
    private javax.swing.JLabel doctor1_timing;
    private javax.swing.JLabel doctor2;
    private javax.swing.JLabel doctor2_timing;
    private javax.swing.JLabel doctor3;
    private javax.swing.JLabel doctor3_timing;
    private javax.swing.JLabel doctor_timings;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables




public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(doctor_timing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(doctor_timing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(doctor_timing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(doctor_timing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new doctor_timing().setVisible(true);
            }
        });
        
    }
}
